name: throtty
description: A URL shortening utility.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.1.3
  flutter_screenutil: ^5.0.0+2
  flutter_dialog_manager: ^1.0.0+4
  gap: ^2.0.0
  http: ^0.13.4
  dartz: ^0.10.1
  equatable: ^2.0.3
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
